### ISSUE TITLE
create user class

### ISSUE THREAD

**Issue by icvotria** [KiranKukar/acebook-mugbook#13]

**Comment by icvotria** [comment]
*deal with database gubbins also

**Comment by kat-mcbrooks** [comment]
` bin/rails generate model User username:string password:text `

Maybe we use something like this command ^^ not sure the difference between string and text

**Comment by helloecho12345** [comment]
https://github.com/kat-mcbrooks/course/blob/main/bookmark_manager/walkthroughs/19.md

Create the user
Our post action must create a user. In the past, we've started by putting our database query in the controller. Now that we have a pattern with Bookmark, though, let's jump straight to using the .create pattern with User:

# in app.rb

post '/users' do
  User.create(email: params[:email], password: params[:password])
  redirect '/bookmarks'
end
Let's implement a test for creating a User like this, using the persisted_data helper method to check that the user has been created in the database.

# in spec/user_spec.rb
require 'database_helpers'

describe '.create' do
  it 'creates a new user' do
    user = User.create(email: 'test@example.com', password: 'password123')

    persisted_data = persisted_data(table: :users, id: user.id)

    expect(user).to be_a User
    expect(user.id).to eq persisted_data.first['id']
    expect(user.email).to eq 'test@example.com'
  end
end
And let's solve this in lib/user.rb:

# in lib/user.rb

require 'database_connection'

class User
  def self.create(email:, password:)
    result = DatabaseConnection.query(
      "INSERT INTO users (email, password) VALUES($1, $2) RETURNING id, email;",
      [email, password]
    )
    User.new(id: result[0]['id'], email: result[0]['email'])
  end

  attr_reader :id, :email

  def initialize(id:, email:)
    @id = id
    @email = email
  end
end
Notice that we've immediately implemented the pattern from 'wrapping database data in program objects'. That is: User.create returns a User instance.
